In [14]:
import numpy as np

In [15]:
epoch_0 = np.zeros(shape=(5,2))
epoch_1 = np.ones(shape=(5,2))

In [16]:
temp = np.append(epoch_0, epoch_1, axis= 1)

In [17]:
temp

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [18]:
np.append(temp, epoch_1, axis= 1)

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])

In [19]:
np.delete(temp, slice(0,2), axis =1)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
filter

In [21]:
out = filter.filter_data(epoch_0, 250, 1, 50, method='iir', iir_params=None, copy=True, verbose=None)

Setting up band-pass filter from 1 - 50 Hz

IIR filter parameters
---------------------
Butterworth bandpass zero-phase (two-pass forward and reverse) non-causal filter:
- Filter order 16 (effective, after forward-backward)
- Cutoffs at 1.00, 50.00 Hz: -6.02, -6.02 dB

